language: node_js
node_js:
    - "0.10"

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install --quiet -g gulp
    - npm install --quiet -g http-server
    - npm install
    - npm run update-chromedriver
    - npm install --quiet -g bower
    - bower install
    - http-server ./demo/ &

script: gulp
